export const sentences = [
  "Near the car",
  "Stay a while.",
  "Between the lines",
  "A few good men",
  "My own father",
  "Don’t open the door,",
  "In the country",
  "You might be right.",
  "Add it up.",
  "It seemed too good.",
  "Read every story.",
  "Along the way",
  "Below the water",
  "Next time",
  "Plants and flowers",
  "It’s hard to open.",
  "Will it last?",
  "Something good",
  "Keep it up.",
  "For example",
  "Plant the trees.",
  "In the beginning",
  "Light the fire.",
  "Those other people",
  "The light in your eyes",
  "A group of friends",
  "In my head",
  "We got together.",
  "Under the earth",
  "We left it here.",
];
